### ISSUE TITLE
Run script in the background

### ISSUE THREAD

**Issue by HVPereira** [Ewlbo/Instagagement#1]
Hello,

Is there any way to run this script in the background? I am trying to make it however since the script requires a account input to start I am not really finding any where how to do it. Would you be so kind to help me? 

By the way is there any way to add custom groups in your JSON? I believe it is a matter of adding it to the JSON and define the number in config.json right?

Hope you can help me and thank you for your work!

**Comment by HVPereira** [comment]
I've edited the preset variable with my username and I've managed to use it in the background with the following command:

nohup python3.7 run.py > log,txt &

Regarding the addition of groups could you support me?

**Comment by Ewlbo** [comment]
Hey, glad this is useful for you. 

I am currently adding terminal arguments so it is possible to run it in background, I have partly released it now in [0.3 version](https://github.com/Ewlbo/Instagagement/releases/tag/0.3) and it can be used like such:
`python run.py --config username/preset_name`
where 'username/preset_name' is the one you would input at start

If you want to specify post on which engagement should be put on (separate with comma):
`python run.py --links link1,link2`
or if you want to randomize posts on which the engagement is done and maybe target different profile on which you want to receive engagement:
`python run.py --target target_username --links random`

As for the groups - it would be beneficial for others if you would list them here and I could add it to template later. As for now, you can add the group in .json with all the necessary parameters and add it to 'available_groups' list with its number (bottom of group_template.json) and then you can add it to your config. I want to streamline this soon.

**Comment by HVPereira** [comment]
WOW you were fast!

I will add the command that I currently use to keep log of the script 

`python -u run.py --config username/preset_name > username/preset_name.log`

I use this as it is useful to me to track everything in a log which the script is doing at the moment. 

Furthermore I would like to add that the release 0.3 does not contain your latest commits so I had to do a git clone of your code. (Not sure if you want to update release 0.3 or not) but I thought it might be of use to you.

Once I  am able to fetch more groups I will add them here.

**Comment by HVPereira** [comment]
Hello again,

I want to add that I had to remove your profanity check as installing this on a raspberry pi is a complete headache. And it is hard to get it working, what do you think of keeping a menu where you would select the features and only load the required libs accordingly? I guess you are using a windows environment but most people run bots on pi's I guess :P Anyhow I am not a good python developer, but I am a user of your scripts so I am just trying to put out some feedback! Regarding the entries they work flawlessly!

**Comment by Ewlbo** [comment]
@HVPereira made the changes with profanity-check, should be available in v0.3
